### PR TITLE
[SHC-82] Add Pull Request Template

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
## What changes were proposed in this pull request?

This PR aims to provide a pull request template like Apache Spark. This also need to be used as a commit message in case of merging.

## How was this patch tested?

N/A.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, @weiqingy . 
Could you review this?

**Comment by weiqingy** [comment]
It's great to have this!!

**Comment by dongjoon-hyun** [comment]
Thank you, @weiqingy .
BTW, it seems that we need to copy manually the PR description when click `Squash and Merge` button. Otherwise, we can make our own GitHub bot for this kind of job.

**Comment by weiqingy** [comment]
I see. Thanks, @dongjoon-hyun .

**Comment by weiqingy** [comment]
Merged this to branch-1.6/branch-2.0/branch-2.1/Master.

**Comment by dongjoon-hyun** [comment]
Wow. Thanks, @weiqingy !

**Pull request merged**
