### PR TITLE
No need to specify 'HBaseTableCatalog.newTable' option when saving data into an existing table

### PR DESCRIPTION
**Pull request by weiqingy**
## What changes were proposed in this pull request?
Now users need to specify 'HBaseTableCatalog.newTable' option when saving data into an existing table. It's unnecessary. This PR is to fix this issue.

## How was this patch tested?
Pass the current test cases and add a new unit test.

### CODE REVIEW

**Comment by weiqingy** [comment]
@dongjoon-hyun Could you please help to review this PR? Thanks.

**Comment by weiqingy** [comment]
Thanks for the review. @dongjoon-hyun

**Comment by weiqingy** [comment]
Merged.

**Comment by dongjoon-hyun** [comment]
BTW, I forgot to mention this. This PR is tested locally and passes the test.

**Pull request merged**
