### PR TITLE
Preserve the columns order of the schema.

### PR DESCRIPTION
**Pull request by lins05**

### CODE REVIEW

**Comment by weiqingy** [comment]
Hi, @lins05 Thanks for the PR. Sorry for the late response. Is there any error happened if the columns order of the schema is not preserved?

**Comment by lins05** [comment]
@weiqingy no errors, just I was a bit surprised when I call `df.show()` and see the order of columns in the printed output is not the same as I provided in the catalog.

**Comment by weiqingy** [comment]
I see. This PR does not change any behavior but might affect the performance (HashMap VS JTreeMap) . cc @dongjoon-hyun

**Comment by weiqingy** [comment]
@lins05  TreeMap uses dictionary order instead of input order. For example, given ('b' -> 2, 'a' -> 1, 'c' ->3), TreeMap seems to return ('a' -> 1, 'b' -> 2, 'c' -> 3) in a dictionary order, not the input order. In the test case, if the input order of catalog is not ("col00", "col01", ..., "col8"), the test case will fail.

**Comment by lins05** [comment]
Ah, right, I should use `LinkedHashMap`.

**Comment by dongjoon-hyun** [comment]
Hi, @lins05 , any update?

**Comment by lins05** [comment]
@dongjoon-hyun @weiqingy I have updated the code and the tests, please take a look.

**Comment by weiqingy** [comment]
LGTM.

**Comment by weiqingy** [comment]
@lins05 Could you make a PR to master and branch 2.1? Thanks.

**Comment by lins05** [comment]
@weiqingy 

- PR to branch-2.1: https://github.com/hortonworks-spark/shc/pull/70
- PR to master: https://github.com/hortonworks-spark/shc/pull/71

**Pull request merged**
