### PR TITLE
Update examples after adding Phoenix coder support

### PR DESCRIPTION
**Pull request by weiqingy**
## What changes were proposed in this pull request?
The format of catalog definition has been changed after adding phoenix coder support. This PR is to update the catalog definition in SHC examples.

## How was this patch tested?
Build passed.

### CODE REVIEW

**Comment by weiqingy** [comment]
Hi, @dongjoon-hyun Could you please help to review this PR? Thanks. 
cc: @bikassaha @merlintang

**Comment by dongjoon-hyun** [comment]
Sure. @weiqingy .

**Comment by dongjoon-hyun** [comment]
+1 LGTM. Please merge this with the commit message. :)

**Comment by weiqingy** [comment]
Thanks, @dongjoon-hyun . I have merged this with the PR description. :)

**Pull request merged**
